---
# Copyright 2018 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '2'
services:
  onos-subscriber-agent:
    image: "${REGISTRY}${REPOSITORY}onos-subscriber-agent:${DOCKER_TAG}"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: [
      "/app",
      "-kafka-brokers=${DOCKER_HOST_IP}:9092",
      "-kafka-topic=authentication.events",
      "-onos-user=onos",
      "-onos-password=rocks",
      "-onos-address=${DOCKER_HOST_IP}:8181"
    ]
    networks:
    - default
    restart: unless-stopped

networks:
  default:
    driver: bridge
